In [ ]:
import requests
# Import the json library
import json
import pandas as pd
from IPython.core.display import clear_output

from warnings import warn
from time import time
from time import sleep
from random import randint

In [243]:
base = "https://games.crossfit.com/competitions/api/v1/competitions/"
start = base + "open/2017/leaderboards"
parameters = {"regional": 0}

In [244]:
#region = 2 is worldwide
divisionList = [1,2,11]

In [245]:
headers = {
    'User-Agent': 'James Chapman, example.com',
    'From': 'chapmanjlc@gmail.com'
}

In [246]:
df = pd.DataFrame()

yearList = []
competitionTypeList = []

affilliateNameList= []
ageList = []
competitorIdList = []
competitorNameList = []
genderList = []
heightList = []
professionList = []

divisionIdList = []
professionList = []
regionIdList = []
regionNameList = [] ###
teamCaptainList = []
weightList = []

scoreOverallList= []
scoreOverallRank= []

scoreOneList = []
scoreTwoList = []
scoreThreeList = []
scoreFourList = []
scoreFiveList = []
scoreSixList = []

scoreOneDisplayList = []
scoreTwoDisplayList = []
scoreThreeDisplayList = []
scoreFourDisplayList = []
scoreFiveDisplayList = []
scoreSixDisplayList = []

scoreOneRankList = []
scoreTwoRankList = []
scoreThreeRankList = []
scoreFourRankList = []
scoreFiveRankList = []
scoreSixRankList = []

errorList = []

In [247]:
start_time = time()
requestcount = 0

In [ ]:
for division in divisionList:

    parameters['division']=division
    parameters['page']=1
    
    requestcount =0
    
    # Make a get request with the parameters.
    response = requests.get(start, params=parameters,headers = headers)
    numPages = response.json()['totalpages']

    for i in range(1,numPages+1):

        try:
            parameters['page']=i

            # Monitor the requests
            requestcount += 1
            elapsed_time = time() - start_time
            print('Request:{} of {} for Division {}; Errors: {} Frequency: {} requests/s'.format(requestcount, numPages, division,len(errorList),requestcount/elapsed_time))
            clear_output(wait = True)

            response = requests.get(start, params=parameters, headers = headers)

            # try again
            #if response.json()['statusCode'] == 408:
            #    response = requests.get(start, params=parameters, headers = headers)


            # Throw a warning for non-200 status codes
            if response.status_code != 200:
                warn('Request: {}; Status code: {}'.format(requests, response.status_code))

            data = response.json()
            table = pd.DataFrame.from_dict(data['athletes'])

            #entrant and scores are both html ad need converted to table
            entranttable = table
            scorejson = json.loads(table['scores'].to_json(orient='records'))
            scoretable = pd.DataFrame.from_dict(scorejson)

            #gets record count
            records = len(entranttable)

            #creates list for types of competition
            yearList.append(['2017'] * records) #TODO: hardcoded because not in this version of API
            competitionTypeList.append(['open'] * records) #TODO: hardcoded because not in this version of API

            #creates entrant lists
            affilliateNameList.append(entranttable['affiliate'])
            ageList.append(entranttable['age'])
            competitorIdList.append(entranttable['userid'])
            competitorNameList.append(entranttable['name'])
            genderList.append([division] * records) #TODO: hardcoded because not in this version of API
            heightList.append(entranttable['height'])

            divisionIdList.append(entranttable['divisionid'])
            professionList.append([1] * records) #TODO: hardcoded because not in this version of API
            regionIdList.append(entranttable['regionid'])
            regionNameList.append(entranttable['region'])
            teamCaptainList.append(['NA'] * records) #TODO: hardcoded because not in this version of API
            weightList.append(entranttable['weight'])

            #this on return so doing it from records not multiplying out

            #score Lists
            scoreOverallList.append(entranttable['overallscore'])
            scoreOverallRank.append(entranttable['overallrank'])
            scoreOneList.append(pd.DataFrame.from_dict(json.loads(scoretable[0].to_json(orient='records')))['scoredetails'])
            scoreTwoList.append(pd.DataFrame.from_dict(json.loads(scoretable[1].to_json(orient='records')))['scoredetails'])
            scoreThreeList.append(pd.DataFrame.from_dict(json.loads(scoretable[2].to_json(orient='records')))['scoredetails'])
            scoreFourList.append(pd.DataFrame.from_dict(json.loads(scoretable[3].to_json(orient='records')))['scoredetails'])
            scoreFiveList.append(pd.DataFrame.from_dict(json.loads(scoretable[4].to_json(orient='records')))['scoredetails'])

            scoreOneDisplayList.append(pd.DataFrame.from_dict(json.loads(scoretable[0].to_json(orient='records')))['scoredisplay'])
            scoreTwoDisplayList.append(pd.DataFrame.from_dict(json.loads(scoretable[1].to_json(orient='records')))['scoredisplay'])
            scoreThreeDisplayList.append(pd.DataFrame.from_dict(json.loads(scoretable[2].to_json(orient='records')))['scoredisplay'])
            scoreFourDisplayList.append(pd.DataFrame.from_dict(json.loads(scoretable[3].to_json(orient='records')))['scoredisplay'])
            scoreFiveDisplayList.append(pd.DataFrame.from_dict(json.loads(scoretable[4].to_json(orient='records')))['scoredisplay'])

            scoreOneRankList.append(pd.DataFrame.from_dict(json.loads(scoretable[0].to_json(orient='records')))['workoutrank'])
            scoreTwoRankList.append(pd.DataFrame.from_dict(json.loads(scoretable[1].to_json(orient='records')))['workoutrank'])
            scoreThreeRankList.append(pd.DataFrame.from_dict(json.loads(scoretable[2].to_json(orient='records')))['workoutrank'])
            scoreFourRankList.append(pd.DataFrame.from_dict(json.loads(scoretable[3].to_json(orient='records')))['workoutrank'])
            scoreFiveRankList.append(pd.DataFrame.from_dict(json.loads(scoretable[4].to_json(orient='records')))['workoutrank'])

            # Pause the loop
            sleep(randint(8,15)/100)
        
        except:
            errorList.append([parameters]+[response.content])

Request:16 of 4291 for Division 1; Errors: 0 Frequency: 1.094036427285727 requests/s

In [239]:
allData = pd.DataFrame({'yearList':[y for x in yearList for y in x],
                'competitionType':[y for x in competitionTypeList for y in x],
                'regionId':[y for x in regionIdList for y in x],
                'divisionId':[y for x in divisionIdList for y in x],
                'competitorId':[y for x in competitorIdList for y in x],
                'competitorName':[y for x in competitorNameList for y in x],
                'age':[y for x in ageList for y in x],
                'gender':[y for x in genderList for y in x],
                'height':[y for x in heightList for y in x],
                'affilliateName':[y for x in affilliateNameList for y in x],
                                
                'profession':[y for x in professionList for y in x],
                'affilliateName':[y for x in affilliateNameList for y in x],
                'regionId':[y for x in regionIdList for y in x],
                'regionName':[y for x in regionNameList for y in x],
                        
                'teamCaptain':[y for x in teamCaptainList for y in x],
                'weight':[y for x in weightList for y in x],
              
                'OverallScore': [y for x in scoreOverallList for y in x],
                'OverallScoreRank': [y for x in scoreOverallRank for y in x],
                'scoreOne':[y for x in scoreOneList for y in x],
                'scoreTwo':[y for x in scoreTwoList for y in x],
                'scoreThree':[y for x in scoreThreeList for y in x],
                'scoreFour':[y for x in scoreFourList for y in x],
                'scoreFive':[y for x in scoreFiveList for y in x],
                        
                'scoreOneDisplay':[y for x in scoreOneDisplayList for y in x],
                'scoreTwoDisplay':[y for x in scoreTwoDisplayList for y in x],
                'scoreThreeDisplay':[y for x in scoreThreeDisplayList for y in x],
                'scoreFourDisplay':[y for x in scoreFourDisplayList for y in x],
                'scoreFiveDisplay':[y for x in scoreFiveDisplayList for y in x],
            
                'scoreOneRank':[y for x in scoreOneRankList for y in x],
                'scoreTwoRank':[y for x in scoreTwoRankList for y in x],
                'scoreThreeRank':[y for x in scoreThreeRankList for y in x],
                'scoreFourRank':[y for x in scoreFourRankList for y in x],
                'scoreFiveRank':[y for x in scoreFiveRankList for y in x]
             }
)

In [240]:
allData.head()

,yearList,competitionType,regionId,divisionId,competitorId,competitorName,age,gender,height,affilliateName,...,scoreOneDisplay,scoreTwoDisplay,scoreThreeDisplay,scoreFourDisplay,scoreFiveDisplay,scoreOneRank,scoreTwoRank,scoreThreeRank,scoreFourRank,scoreFiveRank
0,2017,open,11,1,153604,Mathew Fraser,27,1,"5'7""",,...,10:23,222 reps,17:47,327 reps,6:24,20,15,3,1,1
1,2017,open,15,1,2725,Noah Ohlsen,26,1,"5'7""",,...,10:38,223 reps,19:28,303 reps,6:38,50,5,19,33,11
2,2017,open,4,1,180541,Alex Vigneault,25,1,"5'11""",,...,10:38,219 reps,18:35,320 reps,6:54,50,37,6,5,41
3,2017,open,7,1,81616,Björgvin Karl Guðmundsson,24,1,178 cm,,...,10:50,224 reps,19:03,304 reps,7:00,107,3,13,30,68
4,2017,open,10,1,388740,Anthony Davis,22,1,"5'9""",,...,10:34,215 reps,19:48,300 reps,6:41,41,113,27,51,17

In [241]:
len(errorList)

0

In [231]:
# where werwe errors
pd.DataFrame(errorList)

Empty DataFrame
Columns: []
Index: []

In [242]:
allData.to_csv('data2017.csv')

In [ ]:
#lots of tables = bad
for i in range(1,numPages+1):
    parameters['page']=i
    response = requests.get(start, params=parameters, headers = headers)
    data = response.json()
    table = pd.DataFrame.from_dict(data['leaderboardRows'])

    #entrant and scores are both html ad need converted to table
    entrantjson = json.loads(table['entrant'].to_json(orient='records'))
    entranttable = pd.DataFrame.from_dict(entrantjson)
    scorejson = json.loads(table['scores'].to_json(orient='records'))
    scoretable = pd.DataFrame.from_dict(scorejson)
    df = df.append(pd.merge(entrant, scoretable, left_index=True, right_index=True))
  
scoreOne= scoreOne.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[0].to_json(orient='records'))), left_index=True, right_index=True))
    scoreTwo= scoreTwo.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[1].to_json(orient='records'))), left_index=True, right_index=True))
    scoreThree= scoreThree.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[2].to_json(orient='records'))), left_index=True, right_index=True))
    scoreFour= scoreFour.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[3].to_json(orient='records'))), left_index=True, right_index=True))
    scoreFive= scoreFive.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[4].to_json(orient='records'))), left_index=True, right_index=True))
    scoreSix= scoreSix.append(pd.merge(entrant[['competitorId']], pd.DataFrame.from_dict(json.loads(scoretable[5].to_json(orient='records'))), left_index=True, right_index=True))

In [33]:
#2018 missing {'regional': 0, 'division': 11, 'page': 74}
pd.DataFrame(errorList)

,0,1
0,"{'regional': 0, 'division': 11, 'page': 74}","b'{\n\t""version"":3,\n\t""dataType"":""LEADERBOARD..."